version: '3.9'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=fcds
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=db
    volumes:
      - ./db:/docker-entrypoint-dbdb.d/:ro
      - ./db/data:/var/lib/mysql
      - ./db:/db
    ports:
      - "3304:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    links:
      - 'db:db'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped

  web:
    links:
      - 'db:db'
      - 'phpmyadmin:phpmyadmin'   
    build: ./app 
    container_name: mywebsite
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app 
    # depends_on:
    #   - db
    # environment:
    # - MYSQL_DATABASE=fcds
    # - MYSQL_USER=root
    # - MYSQL_PASSWORD=root
    # - MYSQL_HOST=db  